/**
 **************************************************************************************
 * @file    Key.h
 * @brief   key 
 *
 * @author  pi
 * @version V1.0.0
 *
 * $Created: 2018-1-11 17:40:00$
 *
 * @Copyright (C) 2018, Shanghai Mountain View Silicon Co.,Ltd. All rights reserved.
 **************************************************************************************
 */

#include "app_config.h"
#include "app_message.h"

#ifndef __USER_ENUM_H__
#define __USER_ENUM_H__

#ifdef __cplusplus
extern "C" {
#endif//__cplusplus

//***********自定义通用枚举*******************************//
//程序状态
typedef enum _USER_PROGRAM_STATE
{
	PROGRAM_UNKNOW = 0,
		
	PROGRAM_STARTING,	
	PROGRAM_RUNNING,
	PROGRAM_DEEPSLEEPING,
	PROGRAM_FAKE_DEEPSLEEPING,	//假关机
	PROGRAM_POWERON_SLEEPING,	//假关机
}USER_PROGRAM_STATE;

//串口消息ID
typedef enum _UartMessageId
{
	UART_UPDATE_NONE = 0x00,

	//提示音
	UART_UPDATE_REMIND_KAIJI,
	UART_UPDATE_REMIND_GUANJI,
	UART_UPDATE_REMIND_DLGUODI,

	UART_UPDATE_REMIND_BTMODE,
	UART_UPDATE_REMIND_UPMODE,
	UART_UPDATE_REMIND_TFMODE,
	UART_UPDATE_REMIND_AUXMODE,
	UART_UPDATE_REMIND_HDMIMODE,
	UART_UPDATE_REMIND_OPTMODE,
	UART_UPDATE_REMIND_COAMODE,
	UART_UPDATE_REMIND_TWSMODE,
	UART_UPDATE_REMIND_SHENGKAMODE,

	UART_UPDATE_REMIND_BTCONNECT,
	UART_UPDATE_REMIND_BTDISCONNECT,
	UART_UPDATE_REMIND_TWSCONNECT,
	UART_UPDATE_REMIND_TWSDISCONNECT,

	UART_UPDATE_REMIND_LUYIN,
	UART_UPDATE_REMIND_STOPREC,
	UART_UPDATE_REMIND_REC_REPLAY,
	UART_UPDATE_REMIND_RECFILE_DEL,

	UART_UPDATE_REMIND_NUM_0,
	UART_UPDATE_REMIND_NUM_1,
	UART_UPDATE_REMIND_NUM_2,
	UART_UPDATE_REMIND_NUM_3,
	UART_UPDATE_REMIND_NUM_4,
	UART_UPDATE_REMIND_NUM_5,
	UART_UPDATE_REMIND_NUM_6,
	UART_UPDATE_REMIND_NUM_7,
	UART_UPDATE_REMIND_NUM_8,
	UART_UPDATE_REMIND_NUM_9,

	//mainAppCt变量改变
	UART_UPDATE_MAINAPP_MUSIC_VOL,
	UART_UPDATE_MAINAPP_MUSIC_TREB,
	UART_UPDATE_MAINAPP_MUSIC_BASS,
	UART_UPDATE_MAINAPP_MIC_VOL,
	UART_UPDATE_MAINAPP_GUITAR_VOL,
	UART_UPDATE_MAINAPP_MIC_TREB,
	UART_UPDATE_MAINAPP_MIC_BASS,
	UART_UPDATE_MAINAPP_REVBER_VOL,
	UART_UPDATE_MAINAPP_MUTE,
	UART_UPDATE_MAINAPP_HDMI_MUTE,

	//gCtrlVars变量改变
	UART_UPDATE_GCTRLVARS_MIC_FRIST,
	UART_UPDATE_GCTRLVARS_VOLCUT,
	UART_UPDATE_GCTRLVARS_EARPHONE,
	UART_UPDATE_GCTRLVARS_MIC,
	UART_UPDATE_GCTRLVARS_MIC2,

	//userVar变量改变
	UART_UPDATE_USERVAR_MODE,

	//状态改变
	UART_UPDATE_STATE_PARAM,		//双芯片开机后，同步参数用

	UART_UPDATE_VERSION,
}UartMessageId;
	
typedef enum _USER_CHECK_TYPE		//各种状态枚举
{
	CHECK_TYPE_NONE = 0,
	CHECK_TYPE_SUM8,
	CHECK_TYPE_SUM16,		
	CHECK_TYPE_CRC8,	
	CHECK_TYPE_CRC16_MODBUS,
}USER_CHECK_TYPE;
	
typedef enum _USER_PWM_STATE		//各种状态枚举
{
	PWM_STATE_LOW 		= 0,		//全低
	PWM_STATE_ADD 		= 1,		//逐渐加
	PWM_STATE_SUB 		= 2,		//逐渐减
	PWM_STATE_HIGH 		= 3,		//全高
}USER_PWM_STATE;

typedef enum _LED_TYPE
{
	NORMAL_TYPE = 0,		//普通灯效
	
	MUSIC_VOL_TYPE,			//音乐音量灯效
	MIC_VOL_TYPE,			//麦音量灯效
	GUITAR_VOL_TYPE,		//吉他音量灯效
	MONITOR_VOL_TYPE,		//DAC0音量灯效
	RECORD_VOL_TYPE,		//DACX音量灯效
	Other_VOL_TYPE,			//Other信号检测灯效
	BT_CONNECTED_TYPE,
	LED_BRIGHTNESS_TYPE,
}LED_TYPE;

typedef enum _FLUSH_TIME
{
	FLUSH_TIME_300MS = 0,	//300MS
	FLUSH_TIME_500MS,	
	FLUSH_TIME_1S,	
	
	FLUSH_TIME_MAX,
}FLUSH_TIME;

#ifdef __cplusplus
}
#endif//__cplusplus


#endif


