[main_config]
;home_dir = ../../
home_dir = .
default_dest_lib = middleware/bluetooth/libBtStack.a

[define_files]
;files to search Macros
file1 = app_src/system_config/bt_config.h

[macro_declare]
;declare Macro Names that should be used
BT_SOURCE_SUPPORT = 0
BLE_SUPPORT = 0
BLE_DUAL_ROLE =0
WIRELESS_SUPPORT = 0

[macro_express]
;expression maps libs should be copy
;logical operator -->
;not, and, or for truth value operator
;comparison operator mapping:
;"eql" stand for ==
;"neql" stand for !=
;"ge" stand for >=
;"le" stand for <=
;"gt" stand for >
;"lt" stand for <
BT_SOURCE_SUPPORT = middleware/bluetooth/libBtStack_BtSource.a > middleware/bluetooth/libBtStack.a
BLE_SUPPORT and BLE_DUAL_ROLE = middleware/bluetooth/libBtStack_ble_double_role.a > middleware/bluetooth/libBtStack.a
not BLE_SUPPORT and not BT_SOURCE_SUPPORT and WIRELESS_SUPPORT = middleware/bluetooth/libBtStack_wireless_noble.a > middleware/bluetooth/libBtStack.a
not BLE_SUPPORT and not BT_SOURCE_SUPPORT and not WIRELESS_SUPPORT = middleware/bluetooth/libBtStack_no_ble.a > middleware/bluetooth/libBtStack.a

[default_copy]
;if no condition hits in macro_express, do following copy
copy1 = middleware/bluetooth/libBtStack_Std.a > middleware/bluetooth/libBtStack.a


