[main_config]
home_dir = .
default_dest_lib = tools/funlist.hhh

[define_files]
;files to search Macros
file1 =   driver/driver/inc/chip_info.h

[macro_declare]
;declare Macro Names that should be used
BP15_ROM_VERSION = 0
BP15_ROM_V1 = 0
BP15_ROM_V2 = 0

[macro_express]
;expression maps libs should be copy
;logical operator -->
;not, and, or for truth value operator
;comparison operator mapping:
;"eql" stand for ==
;"neql" stand for !=
;"ge" stand for >=
;"le" stand for <=
;"gt" stand for >
;"lt" stand for <
BP15_ROM_VERSION eql BP15_ROM_V2 = tools/funlist_rom2.hhh > tools/funlist.hhh

[default_copy]
;if no condition hits in macro_express, do following copy
copy1 = tools/funlist_rom1.hhh > tools/funlist.hhh


